# Start with a Node.js base image
FROM node:20

WORKDIR /app

# Copy app 

COPY portfolioApp/ ./

RUN npm install
RUN npm run build

COPY tools/launch.sh ./

# Expose the port that the Next.js app will run on
EXPOSE 3030

# Start the Next.js app
CMD ["bash", "/app/launch.sh"]
# or start with dev mode
# CMD ["npm", "run", "dev"]